name = "email-worker"
main = "./src/index.ts"
compatibility_date = "2024-09-02"

[observability]
enabled = true
head_sampling_rate = 1

[[d1_databases]]
binding = "DB"
database_name = "$CF_EMAIL_DB_NAME"
database_id = "$CF_EMAIL_DB_ID"
